function PE__problem2(n) {
/*
Problem statement:
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

  function getNextFibTerm(fibs, limit) {
    var L = fibs.length;
    fibs.push((fibs[L-2] + fibs[L-1]));
    // if next term looks like less than the limit,
    // carry on...
    if((fibs[L] + fibs[L-1]) < limit) {
      getNextFibTerm(fibs, limit);
    }
  }

  function solution(x) {
    var sum = 0;
    var fibs = [1, 2];
    var limit;

    limit = x;

    getNextFibTerm(fibs, limit);

    for(i in fibs) {
      if(parseInt(fibs[i]) % 2 === 0) {
        sum += parseInt(fibs[i]);
      }
    }

    return {
      'sum': sum,
      'fibs': fibs
    };
  }

  return solution(n);
}
